# Generated by Django 5.1.2 on 2024-11-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_radiographerprofile_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(upload_to='certificates', verbose_name='Certificate'),
        ),
    ]
