# Generated by Django 5.1.2 on 2024-11-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_radiologistprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('passedYear', models.PositiveIntegerField()),
                ('result', models.FloatField(verbose_name='Result')),
                ('file', models.FileField(upload_to='media/certificates', verbose_name='Certificate')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='radiographerprofile',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='radiologistprofile',
            name='certificate',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='certificate',
            field=models.ManyToManyField(blank=True, to='profiles.certificate'),
        ),
        migrations.AddField(
            model_name='radiographerprofile',
            name='certificate',
            field=models.ManyToManyField(blank=True, to='profiles.certificate'),
        ),
        migrations.AddField(
            model_name='radiologistprofile',
            name='certificate',
            field=models.ManyToManyField(blank=True, to='profiles.certificate'),
        ),
    ]
