# Generated by Django 5.1.2 on 2024-11-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_certificate_remove_adminprofile_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='start',
            field=models.DateField(),
        ),
    ]
