# Generated by Django 5.1.2 on 2024-11-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
