# Generated by Django 5.1.2 on 2024-11-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologist',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Avatar'),
        ),
    ]
