# Generated by Django 5.1.2 on 2024-11-07 05:12

import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rediologist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radiologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('phone', utils.fields.PhoneNumberField(db_index=True, max_length=11, unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(db_index=True, max_length=50, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Avatar')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending')], default='active', max_length=20)),
                ('department', models.ManyToManyField(blank=True, related_name='radiologists', to='account.department')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Rediologist',
        ),
    ]
