# Generated by Django 5.1.2 on 2024-12-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_radiologist_status_alter_user_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Radiologist',
        ),
    ]
