# Generated by Django 5.1.2 on 2024-11-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_radiologist_department_radiologist_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologist',
            name='name',
            field=models.CharField(default='test', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
