# Generated by Django 5.1.2 on 2024-11-07 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_isadmin_user_isradiographer_user_isradiologist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
